name: test

on: push

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - run: cmake -E make_directory $GITHUB_WORKSPACE/build
    - run: cmake .
      working-directory: $GITHUB_WORKSPACE/build
    - run: cmake --build .
      working-directory: $GITHUB_WORKSPACE/build
    - run: liba_tests.exe
      working-directory: $GITHUB_WORKSPACE/build/test-unit/Debug/
